---
- name: Filebeat Playbook
  hosts: webservers
  become: true
  tasks:

  - name: Download MetricBeat .deb package
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install MetricBeat with DPKG
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Copy MetricBeat Configs
    copy:
      src: /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  -  name: Enable and configure MetricBeat docker Modules
     command: metricbeat modules enable docker

  - name: Start Metricbeat
    command: metricbeat setup

    #- name: Metricbeat -e
    #command:  metricbeat -e

  - name: Start filebeat with SystemD
    command: systemctl enable --now metricbeat